
services:
  product-mongo:
    image: mongo:6
    container_name: product-mongo
    restart: always
    ports:
      - "28000:27017"
    volumes:
      - mongo_product_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: productdb
      MONGO_INITDB_ROOT_USERNAME: productuser
      MONGO_INITDB_ROOT_PASSWORD: productpass

volumes:
  mongo_product_data: